# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70ed66675e648f55d6239d41a77edc106e67fdedb22a5683d391548896b86390bb534421ec6a1c7877d90d15ea9beae40814a55bdd090978df280dea94b58a6

test:
  secret_key_base: 56c1c2e9a9d9777b18cfc96e90e209ba770995e387cbfe9cf88a429cc37cfaddfc63e10a1a1e04c9f66fa092c4fea89bd4b89919d7198b6d3986f0048468c87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
